export const UI_CONSTANTS = {
  CAMERA_CAPTURE_QUALITY: 0.92,
  MAX_HISTORY_ITEMS: 20,
  RECOGNIZE_IMAGE_HEIGHT: 128,
  RECOGNIZE_IMAGE_WIDTH: 512,
  DRAW_BACKGROUND_FILL: '#ffffff',
  DRAW_STROKE_COLOR: '#000000',
  DRAW_STROKE_WIDTH: 4,
  SPEECH_RATE_DEFAULT: 0.95,
  SPEECH_PITCH_DEFAULT: 1.0,
  SPEECH_VOLUME_DEFAULT: 1.0,
} as const;
